spring:
    datasource: 
       
        url: jdbc:h2:file:./visitabrennanddb
        driver-class-name: org.h2.Driver
        username: teste
        password: 
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
        defer-datasource-initialization: true 
    thymeleaf:
        cache: false