INSERT INTO visitas (nome_instituicao, cnpj, tipo_instituicao, nome_responsavel, email_responsavel, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('Escola Municipal Frei Caneca', '11.222.333/0001-44', 'ESCOLA_PUBLICA', 'Ana Lúcia Gomes', 'ana.gomes@email.com', '81911112222', '2025-10-12', '09:00', 35, false, 'AGENDADO');
INSERT INTO visitas (nome_instituicao, cnpj, tipo_instituicao, nome_responsavel, email_responsavel, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('Colégio Adventista do Recife', '22.333.444/0001-55', 'ESCOLA_PRIVADA', 'Carlos Pereira', 'carlos.pereira@email.com', '81922223333', '2025-10-12', '10:00', 42, true, 'AGENDADO');
INSERT INTO visitas (nome_instituicao, cnpj, tipo_instituicao, nome_responsavel, email_responsavel, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('Universidade Federal de Pernambuco - UFPE', '33.444.555/0001-66', 'UNIVERSIDADE', 'Mariana Costa', 'mariana.costa@email.com', '81933334444', '2025-10-15', '14:00', 25, false, 'AGENDADO');
INSERT INTO visitas (nome_instituicao, cnpj, tipo_instituicao, nome_responsavel, email_responsavel, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('Empresa de Tecnologia Acme', '44.555.666/0001-77', 'EMPRESA', 'João Silva', 'joao.silva@email.com', '81944445555', '2025-10-17', '11:00', 15, false, 'AGENDADO');
INSERT INTO visitas (nome_instituicao, cnpj, tipo_instituicao, nome_responsavel, email_responsavel, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('Escola Municipal Antônio Carlos', null, 'ESCOLA_PUBLICA', 'Fernanda Lima', 'fernanda.lima@email.com', '81955556666', '2025-09-28', '09:00', 30, true, 'REALIZADO');
INSERT INTO visitas (nome_instituicao, cnpj, tipo_instituicao, nome_responsavel, email_responsavel, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('Instituto de Arte Moderna', null, 'OUTRO', 'Pedro Andrade', 'pedro.andrade@email.com', '81966667777', '2025-10-01', '15:00', 22, false, 'REALIZADO');
INSERT INTO visitas (nome_instituicao, cnpj, tipo_instituicao, nome_responsavel, email_responsavel, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('Grupo de Turismo Sol a Pino', null, 'OUTRO', 'Ricardo Alves', 'ricardo.alves@email.com', '81977778888', '2025-10-20', '10:00', 18, false, 'CANCELADO');
INSERT INTO visitas (nome_instituicao, cnpj, tipo_instituicao, nome_responsavel, email_responsavel, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('GRUPO DE TESTE HOJE', null, 'OUTRO', 'Visitante Teste', 'matheusmelqn@gmail.com', '81999998888', '2025-10-20', '14:00', 10, false, 'AGENDADO');

INSERT INTO visitas (nome_instituicao, nome_responsavel, email_responsavel, tipo_instituicao, telefone_responsavel, data_visita, horario_chegada, numero_visitantes, inclui_pcd, status) VALUES ('Grupo de Avaliação', 'Visitante de Teste de Avaliação', 'matheusmelqn@gmail.com', 'OUTRO', '555555555', '2025-10-19', '11:30', 2, false, 'REALIZADO');